/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DocumentVerification {
  export type DocumentStruct = {
    fileName: string;
    documentHash: string;
    ipfsCID: string;
    timestamp: BigNumberish;
    uploader: AddressLike;
    version: BigNumberish;
  };

  export type DocumentStructOutput = [
    fileName: string,
    documentHash: string,
    ipfsCID: string,
    timestamp: bigint,
    uploader: string,
    version: bigint
  ] & {
    fileName: string;
    documentHash: string;
    ipfsCID: string;
    timestamp: bigint;
    uploader: string;
    version: bigint;
  };
}

export interface DocumentVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "documents"
      | "getDocumentCount"
      | "getDocuments"
      | "storeDocument"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "documents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocumentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDocuments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeDocument",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "documents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDocumentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeDocument",
    data: BytesLike
  ): Result;
}

export interface DocumentVerification extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentVerification;
  waitForDeployment(): Promise<this>;

  interface: DocumentVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  documents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        fileName: string;
        documentHash: string;
        ipfsCID: string;
        timestamp: bigint;
        uploader: string;
        version: bigint;
      }
    ],
    "view"
  >;

  getDocumentCount: TypedContractMethod<[], [bigint], "view">;

  getDocuments: TypedContractMethod<
    [],
    [DocumentVerification.DocumentStructOutput[]],
    "view"
  >;

  storeDocument: TypedContractMethod<
    [
      _fileName: string,
      _hash: string,
      _ipfsCID: string,
      _version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "documents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint] & {
        fileName: string;
        documentHash: string;
        ipfsCID: string;
        timestamp: bigint;
        uploader: string;
        version: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDocumentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDocuments"
  ): TypedContractMethod<
    [],
    [DocumentVerification.DocumentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeDocument"
  ): TypedContractMethod<
    [
      _fileName: string,
      _hash: string,
      _ipfsCID: string,
      _version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
