/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentVerification } from "./DocumentVerification";
export * as factories from "./factories";
export { DocumentVerification__factory } from "./factories/DocumentVerification__factory";
